pip install hydra-core --user
pip install lightning --user
pip install polars --user
pip install transformers --user
pip install datasets --user
pip install adan-pytorch --user
pip install merlin-dataloader --user
pip install rdkit --user
pip install torch_geometric --user
pip install squeezeformer --user
