defaults:
  - _self_
  - preprocessor: chemberta

n_rows: ~
batch_size: 10000000
data_dir: /project/data/lb
output_dir: /project/data/lb
stage: test
overwrite: False
use_cols:
  - non_isomeric_molecule_smiles
